version: 0.0
os: linux
files:
  - source: /
  - destination: /opt/demo-node-app/release
permissions:
  - object: /opt/demo-node-app
  - pattern: "**"
  - owner: ec2-user
  - group: ec2-user
  - mode: 755
hooks:  
  BeforeInstall:
    - location: scripts/before_install.sh
    - timeout: 300
    - runas: root
  AfterInstall:
    - location: scripts/after_install.sh
    - timeout: 300
    - runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
    - timeout: 300
    - runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
    - timeout: 300
    - runas: root
  ValidateService:
    - location: scripts/validate_service.sh
    - timeout: 300
    - runas: root